import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import reactPlugin from 'eslint-plugin-react';
import reactHooksPlugin from 'eslint-plugin-react-hooks';
import jsxA11yPlugin from 'eslint-plugin-jsx-a11y';
import importPlugin from 'eslint-plugin-import';

// Shared TypeScript overrides applied to all three environments (renderer, electron, worker).
// Defined once here to avoid duplicating the same rule set across multiple config objects.
const sharedTsRules = {
  '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type-imports' }],
  '@typescript-eslint/no-unused-vars': [
    'error',
    { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
  ],
  // Strict: every new any requires an inline disable with a TODO
  '@typescript-eslint/no-explicit-any': 'error',
  // Empty interfaces are a common pattern in shadcn/ui component extensions
  '@typescript-eslint/no-empty-object-type': 'warn',
  // Require a description on every @ts-expect-error and ban bare @ts-ignore.
  // (ban-ts-comment ships in the recommended preset with looser defaults; we
  // tighten it here so suppressions must explain themselves.) These are
  // syntactic checks — no type-aware linting required.
  '@typescript-eslint/ban-ts-comment': [
    'error',
    { 'ts-expect-error': 'allow-with-description', 'ts-ignore': true, 'ts-nocheck': true },
  ],
  // When all specifiers in a curly import are type-only, rewrite to a top-level
  // `import type {}` so the import is fully erased at emit (no accidental
  // module-initialisation side effects). Complements consistent-type-imports.
  '@typescript-eslint/no-import-type-side-effects': 'error',
  // Import hygiene (warn-only baseline, auto-fixable). Purely syntactic — no
  // resolver needed, so no eslint-import-resolver-typescript dependency.
  'import/order': [
    'warn',
    {
      groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
      // 'ignore' so the autofix only sorts within groups — it never adds or
      // strips blank lines between groups, respecting the existing style.
      'newlines-between': 'ignore',
      alphabetize: { order: 'asc', caseInsensitive: true },
    },
  ],
  'import/no-duplicates': 'warn',
};

// Accessibility lint for the React/Radix renderer. The recommended ruleset
// ships as `error`; we land it as a non-blocking `warn` baseline (the root
// `lint` script has no `--max-warnings 0`) to be promoted after cleanup.
const jsxA11yWarnRules = Object.fromEntries(
  Object.keys(jsxA11yPlugin.flatConfigs.recommended.rules).map((rule) => [rule, 'warn'])
);

// Same rule set, all disabled — applied to test files (see the trailing test
// override). Tests deliberately order imports for mock hoisting and render
// throwaway fixtures, so the import-hygiene and a11y baselines add noise here.
const jsxA11yOffRules = Object.fromEntries(
  Object.keys(jsxA11yPlugin.flatConfigs.recommended.rules).map((rule) => [rule, 'off'])
);

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      '.wrangler/**',
      'cli/dist/**',
      'cli/fixtures/**',
      'extension/dist/**',
      // Bundled extension output + packaged artifact — generated by esbuild/vsce.
      'vscode-extension/out/**',
      'vscode-extension/*.vsix',
      // Downloaded VS Code + test profile, created by @vscode/test-cli.
      'vscode-extension/.vscode-test/**',
      '*.config.mts',
      // Generated by scripts/build-sandbox-libs.mjs; vendor library sources
      // inlined as strings, regenerated each build.
      'src/features/scripts/lib/sandboxLibraries/bundle.generated.ts',
      // Hand-written shims emulating Node built-ins for the QuickJS sandbox.
      // These intentionally mimic Node-style CJS to be consumed by esbuild's
      // browser-target bundler — they are NOT renderer code.
      'scripts/sandbox-shims/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  // Renderer (src/): React rules + shared TS overrides
  {
    files: ['src/**/*.{ts,tsx}'],
    plugins: {
      react: reactPlugin,
      'react-hooks': reactHooksPlugin,
      'jsx-a11y': jsxA11yPlugin,
      import: importPlugin,
    },
    rules: {
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      'react/display-name': 'warn',
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      ...jsxA11yWarnRules,
      // Deprecated and redundant with label-has-associated-control (which we
      // keep). Disabling avoids double-reporting the same label issues.
      'jsx-a11y/label-has-for': 'off',
      ...sharedTsRules,
    },
    settings: {
      react: { version: '19' },
    },
  },
  // Non-renderer environments: shared TS overrides only
  {
    files: [
      'electron/main/**/*.ts',
      'worker/**/*.ts',
      'echo/**/*.ts',
      'cli/**/*.ts',
      'shared/**/*.ts',
      'vscode-extension/**/*.ts',
    ],
    plugins: {
      import: importPlugin,
    },
    rules: sharedTsRules,
  },
  // Root tests/** — honor the `^_` intentionally-unused convention (the rest of
  // the recommended profile already applies). Colocated tests under src/** get
  // the args/vars ignores from the renderer block above.
  {
    files: ['tests/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
    },
  },
  // Electron main uses require() for CJS-only packages (electron-store, electron-squirrel-startup)
  {
    files: ['electron/main/**/*.ts'],
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
  // Build/codegen scripts — Node, mix of ESM (.mjs) and CJS (.js).
  {
    files: ['scripts/**/*.{mjs,js,cjs}'],
    languageOptions: {
      globals: { ...globals.node },
    },
    rules: {
      'no-console': 'off',
      'no-undef': 'error',
      // scripts/*.js are CJS and use require() intentionally
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
    },
  },
  // VS Code extension build script + .vscode-test config + integration tests —
  // Node ESM (mocha globals for the integration specs). The extension's *.ts
  // source is covered by the non-renderer block above.
  {
    files: ['vscode-extension/**/*.{mjs,js,cjs}'],
    languageOptions: {
      globals: { ...globals.node, ...globals.mocha },
    },
    rules: {
      'no-console': 'off',
      'no-undef': 'error',
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
  // Keep the eagerly-loaded workflow executor + helpers free of React Flow.
  // The graph canvas (`flow-canvas/`) is lazy-loaded so users who never open
  // the Graph tab don't pay the bundle cost. An accidental eager import from
  // anywhere in `lib/**` would defeat the split — this rule catches it at
  // CI time.
  {
    files: ['src/features/workflows/lib/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/flow-canvas/**', '**/components/flow-canvas/**'],
              message:
                'src/features/workflows/lib/** must not import from flow-canvas/** — the canvas is lazy-loaded, eager imports defeat the split.',
            },
            {
              group: ['@xyflow/react', '@dagrejs/dagre', 'dagre'],
              message:
                'React Flow / dagre belong only to the lazy flow-canvas chunk. Move this code there.',
            },
          ],
        },
      ],
    },
  },
  // Test files: exempt from the newly-added import-hygiene + a11y baselines.
  // Placed last so it wins over the renderer/non-renderer blocks above.
  {
    files: ['**/__tests__/**/*.{ts,tsx}', '**/*.{test,spec}.{ts,tsx}'],
    plugins: {
      import: importPlugin,
      'jsx-a11y': jsxA11yPlugin,
    },
    rules: {
      'import/order': 'off',
      'import/no-duplicates': 'off',
      ...jsxA11yOffRules,
    },
  }
);
