/**
 * Bruno exporter — round-trip + targeted format tests.
 *
 * The strongest signal that the exporter is correct is round-trip:
 * Restura Collection → export to .bru → re-import → assert deep equality on
 * the canonical Collection shape (ignoring auto-generated UUIDs).
 *
 * Any drift between importer and exporter shows up here.
 */

import { describe, it, expect } from 'vitest';
import type { Collection, CollectionItem, Environment } from '@/types';
import { exportBrunoCollection, exportBrunoRequest } from '../bruno-exporter';
import { importBrunoCollection } from '../importers/bruno';

/**
 * Strip every `id` field from a Collection / CollectionItem / Environment tree
 * so deep-equality doesn't fail on autogenerated UUIDs.
 */
function stripIds<T>(value: T): T {
  if (Array.isArray(value)) return value.map(stripIds) as unknown as T;
  if (value && typeof value === 'object') {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      if (k === 'id') continue;
      out[k] = stripIds(v);
    }
    return out as T;
  }
  return value;
}

function makeCollection(items: CollectionItem[], variables?: Collection['variables']): Collection {
  return {
    id: 'c-1',
    name: 'Round Trip',
    items,
    ...(variables ? { variables } : {}),
  };
}

describe('Bruno exporter — round trip', () => {
  it('preserves a simple GET request with headers and query params', async () => {
    const source = makeCollection([
      {
        id: 'i-1',
        name: 'list-users',
        type: 'request',
        request: {
          id: 'r-1',
          name: 'list-users',
          type: 'http',
          method: 'GET',
          url: 'https://api.example.com/users',
          headers: [
            { id: 'h-1', key: 'Accept', value: 'application/json', enabled: true },
            { id: 'h-2', key: 'X-Trace', value: 'abc', enabled: false },
          ],
          params: [
            { id: 'p-1', key: 'page', value: '1', enabled: true },
            { id: 'p-2', key: 'limit', value: '20', enabled: true },
          ],
          body: { type: 'none' },
          auth: { type: 'none' },
        },
      },
    ]);

    const exported = await exportBrunoCollection(source);
    expect(exported.kind).toBe('directory');
    if (exported.kind !== 'directory') return;

    const reimported = await importBrunoCollection({
      kind: 'directory',
      entries: exported.entries,
    });

    expect(reimported.warnings).toEqual([]);
    expect(stripIds(reimported.collection.items)).toEqual(stripIds(source.items));
  });

  it('preserves JSON body', async () => {
    const source = makeCollection([
      {
        id: 'i-1',
        name: 'create-user',
        type: 'request',
        request: {
          id: 'r-1',
          name: 'create-user',
          type: 'http',
          method: 'POST',
          url: 'https://api.example.com/users',
          headers: [],
          params: [],
          body: { type: 'json', raw: '{"name":"alice"}' },
          auth: { type: 'none' },
        },
      },
    ]);

    const exported = await exportBrunoCollection(source);
    if (exported.kind !== 'directory') throw new Error('expected directory output');
    const reimported = await importBrunoCollection({
      kind: 'directory',
      entries: exported.entries,
    });

    const item = reimported.collection.items[0];
    expect(item).toBeDefined();
    if (!item || item.type !== 'request' || item.request?.type !== 'http') {
      throw new Error('expected an http request after round trip');
    }
    expect(item.request.method).toBe('POST');
    expect(item.request.body).toEqual({ type: 'json', raw: '{"name":"alice"}' });
  });

  it('preserves Basic + Bearer + API-key auth across round trip', async () => {
    const source = makeCollection([
      {
        id: 'i-basic',
        name: 'basic',
        type: 'request',
        request: {
          id: 'r-basic',
          name: 'basic',
          type: 'http',
          method: 'GET',
          url: 'https://example.com/basic',
          headers: [],
          params: [],
          body: { type: 'none' },
          auth: { type: 'basic', basic: { username: 'admin', password: 's3cret' } },
        },
      },
      {
        id: 'i-bearer',
        name: 'bearer',
        type: 'request',
        request: {
          id: 'r-bearer',
          name: 'bearer',
          type: 'http',
          method: 'GET',
          url: 'https://example.com/bearer',
          headers: [],
          params: [],
          body: { type: 'none' },
          auth: { type: 'bearer', bearer: { token: 'tok-123' } },
        },
      },
      {
        id: 'i-apikey',
        name: 'apikey',
        type: 'request',
        request: {
          id: 'r-apikey',
          name: 'apikey',
          type: 'http',
          method: 'GET',
          url: 'https://example.com/apikey',
          headers: [],
          params: [],
          body: { type: 'none' },
          auth: { type: 'api-key', apiKey: { key: 'X-Api-Key', value: 'abcd', in: 'header' } },
        },
      },
    ]);

    const exported = await exportBrunoCollection(source);
    if (exported.kind !== 'directory') throw new Error('expected directory output');
    const reimported = await importBrunoCollection({
      kind: 'directory',
      entries: exported.entries,
    });

    expect(reimported.warnings).toEqual([]);
    const items = reimported.collection.items;
    // Items may be reordered alphabetically by Bruno's filename layout; index by name.
    const byName = new Map(items.map((i) => [i.name, i]));
    expect(byName.get('basic')?.request?.auth).toEqual({
      type: 'basic',
      basic: { username: 'admin', password: 's3cret' },
    });
    expect(byName.get('bearer')?.request?.auth).toEqual({
      type: 'bearer',
      bearer: { token: 'tok-123' },
    });
    const apikeyAuth = byName.get('apikey')?.request?.auth;
    expect(apikeyAuth).toMatchObject({
      type: 'api-key',
      apiKey: { key: 'X-Api-Key', value: 'abcd', in: 'header' },
    });
  });

  it('preserves folder hierarchy', async () => {
    const source = makeCollection([
      {
        id: 'f-1',
        name: 'users',
        type: 'folder',
        items: [
          {
            id: 'f-1-1',
            name: 'auth',
            type: 'folder',
            items: [
              {
                id: 'r-login',
                name: 'login',
                type: 'request',
                request: {
                  id: 'r-login-inner',
                  name: 'login',
                  type: 'http',
                  method: 'POST',
                  url: 'https://example.com/login',
                  headers: [],
                  params: [],
                  body: { type: 'json', raw: '{}' },
                  auth: { type: 'none' },
                },
              },
            ],
          },
        ],
      },
    ]);

    const exported = await exportBrunoCollection(source);
    if (exported.kind !== 'directory') throw new Error('expected directory output');

    // Verify the file layout matches Bruno's: users/auth/login.bru
    const relPaths = exported.entries.map((e) => e.relativePath);
    expect(relPaths).toContain('users/auth/login.bru');

    const reimported = await importBrunoCollection({
      kind: 'directory',
      entries: exported.entries,
    });
    expect(reimported.warnings).toEqual([]);

    // Drill into the reimported tree.
    const users = reimported.collection.items[0];
    expect(users?.type).toBe('folder');
    const auth = users?.items?.[0];
    expect(auth?.type).toBe('folder');
    const login = auth?.items?.[0];
    expect(login?.type).toBe('request');
    expect(login?.request?.name).toBe('login');
  });

  it('preserves pre-request and test scripts', async () => {
    const source = makeCollection([
      {
        id: 'i-scripted',
        name: 'scripted',
        type: 'request',
        request: {
          id: 'r-scripted',
          name: 'scripted',
          type: 'http',
          method: 'GET',
          url: 'https://example.com/scripted',
          headers: [],
          params: [],
          body: { type: 'none' },
          auth: { type: 'none' },
          preRequestScript: "console.log('before');",
          testScript: "pm.test('ok', function () { pm.response.to.have.status(200); });",
        },
      },
    ]);

    const exported = await exportBrunoCollection(source);
    if (exported.kind !== 'directory') throw new Error('expected directory output');
    const reimported = await importBrunoCollection({
      kind: 'directory',
      entries: exported.entries,
    });
    const req = reimported.collection.items[0]?.request;
    expect(req?.type).toBe('http');
    if (req?.type !== 'http') return;
    expect(req.preRequestScript).toContain("console.log('before')");
    // Bruno re-import normalizes the Postman pm.* namespace to native rs.*.
    expect(req.testScript).toContain("rs.test('ok'");
  });

  it('preserves environments', async () => {
    const source = makeCollection([]);
    const environments: Environment[] = [
      {
        id: 'e-dev',
        name: 'dev',
        variables: [
          { id: 'v-1', key: 'baseUrl', value: 'https://dev.example.com', enabled: true },
          { id: 'v-2', key: 'apiKey', value: 'secret', enabled: true, secret: true },
        ],
      },
    ];

    const exported = await exportBrunoCollection(source, { environments });
    if (exported.kind !== 'directory') throw new Error('expected directory output');
    expect(exported.entries.find((e) => e.relativePath === 'environments/dev.bru')).toBeDefined();

    const reimported = await importBrunoCollection({
      kind: 'directory',
      entries: exported.entries,
    });
    expect(reimported.environments).toBeDefined();
    expect(reimported.environments?.[0]?.name).toBe('dev');
    const vars = reimported.environments?.[0]?.variables ?? [];
    const byKey = new Map(vars.map((v) => [v.key, v]));
    expect(byKey.get('baseUrl')?.value).toBe('https://dev.example.com');
    expect(byKey.get('apiKey')?.secret).toBe(true);
  });
});

describe('Bruno exporter — single request', () => {
  it('produces a parseable .bru text for a single request', async () => {
    const text = await exportBrunoRequest({
      id: 'r-1',
      name: 'health',
      type: 'http',
      method: 'GET',
      url: 'https://example.com/health',
      headers: [],
      params: [],
      body: { type: 'none' },
      auth: { type: 'none' },
    });

    expect(text).toContain('meta {');
    expect(text).toContain('name: health');
    expect(text).toMatch(/get\s*\{/);
    expect(text).toContain('url: https://example.com/health');

    // Round-trip the single text back through the importer.
    const reimported = await importBrunoCollection({ kind: 'single', content: text });
    const item = reimported.collection.items[0];
    expect(item?.name).toBe('health');
    expect(item?.request?.type).toBe('http');
  });
});

describe('Bruno exporter — filename sanitisation', () => {
  it('replaces forbidden characters in request names', async () => {
    const source = makeCollection([
      {
        id: 'i-1',
        name: 'a/b: name?',
        type: 'request',
        request: {
          id: 'r-1',
          name: 'a/b: name?',
          type: 'http',
          method: 'GET',
          url: 'https://example.com/x',
          headers: [],
          params: [],
          body: { type: 'none' },
          auth: { type: 'none' },
        },
      },
    ]);

    const exported = await exportBrunoCollection(source);
    if (exported.kind !== 'directory') throw new Error('expected directory output');
    const files = exported.entries.map((e) => e.relativePath);
    // None of the forbidden chars (sans `/`, which is a path separator and
    // legitimately appears between segments) should leak into the path.
    const FORBIDDEN = /[\\:*?"<>|]/;
    for (const f of files) {
      expect(FORBIDDEN.test(f)).toBe(false);
    }
    expect(files.some((f) => f.endsWith('.bru') && f.includes('a_b_name'))).toBe(true);
  });
});

describe('Bruno exporter — lossy-export warnings', () => {
  it('emits a non-http-request warning for gRPC/WS/SSE/MCP requests', async () => {
    const source = makeCollection([
      {
        id: 'i-grpc',
        name: 'list-users-grpc',
        type: 'request',
        request: {
          id: 'r-grpc',
          name: 'list-users-grpc',
          type: 'grpc',
          // Minimal shape — exporter only reads url+name for non-HTTP stubs.
          url: 'grpc://api.example.com',
          method: 'ListUsers',
          methodType: 'unary',
          service: 'users.UserService',
          requestBody: '{}',
          metadata: [],
          auth: { type: 'none' },
        } as unknown as CollectionItem['request'],
      },
    ]);

    const exported = await exportBrunoCollection(source);
    if (exported.kind !== 'directory') throw new Error('expected directory output');
    expect(exported.warnings).toHaveLength(1);
    expect(exported.warnings[0]?.kind).toBe('non-http-request');
    expect(exported.warnings[0]?.path).toMatch(/list-users-grpc\.bru$/);
    expect(exported.warnings[0]?.message).toMatch(/Bruno only supports HTTP/);
  });

  it('reports zero warnings for an HTTP-only collection', async () => {
    const source = makeCollection([
      {
        id: 'i-1',
        name: 'ok',
        type: 'request',
        request: {
          id: 'r-1',
          name: 'ok',
          type: 'http',
          method: 'GET',
          url: 'https://example.com/ok',
          headers: [],
          params: [],
          body: { type: 'none' },
          auth: { type: 'none' },
        },
      },
    ]);
    const exported = await exportBrunoCollection(source);
    if (exported.kind !== 'directory') throw new Error('expected directory output');
    expect(exported.warnings).toEqual([]);
  });

  it('throws in strict mode when a non-HTTP request is encountered', async () => {
    const source = makeCollection([
      {
        id: 'i-ws',
        name: 'subscribe',
        type: 'request',
        request: {
          id: 'r-ws',
          name: 'subscribe',
          type: 'websocket',
          url: 'wss://example.com/socket',
        } as unknown as CollectionItem['request'],
      },
    ]);
    await expect(exportBrunoCollection(source, { strict: true })).rejects.toThrow(
      /Bruno only supports HTTP/
    );
  });
});
