/**
 * Public entry for the Postman-compatible library bundle.
 *
 * `loadSandboxLibraries()` uses a real dynamic `import()` of
 * `bundle.generated.ts` so Vite code-splits the (~2MB raw / ~600KB gz)
 * library bundle into its own async chunk. The entry bundle stays slim;
 * the libraries land in a separate hash-named asset that's only fetched
 * the first time any script-using feature runs.
 *
 * The QuickJS sandbox consumes these sources as strings (it has no
 * ES-module loader). The exported `buildRequireShimSource()` produces
 * the JS source the executor eval's inside QuickJS to wire `require(name)`.
 *
 * Note on the generated file:
 *   `bundle.generated.ts` is a build artifact regenerated by
 *   `scripts/build-sandbox-libs.mjs` (invoked by the Vite plugin and the
 *   CLI prebuild). A tiny TS stub is committed so type-check passes
 *   before any build has run — the stub's empty maps mean `require()`
 *   throws "Cannot find module" at runtime until the real bundle lands.
 */

export interface SandboxLibraryBundle {
  /** Per-library IIFE source. Eval'd inside QuickJS. */
  sources: Record<string, string>;
  /** Per-library `globalThis.<x>` name the IIFE assigns its exports to. */
  globalNames: Record<string, string>;
  /** Tiny prelude with Node-built-in shims + atob/btoa. Runs before any lib. */
  prelude: string;
}

let cached: Promise<SandboxLibraryBundle> | null = null;

/**
 * Lazy-load the library bundle. Resolves to the same module object on
 * every call within a renderer session — the cost is paid exactly once,
 * the first time a script runs. Errors propagate to the caller (the
 * executor logs them as a soft failure so the basic `pm.test` /
 * `pm.variables` surface still works for diagnostics).
 */
export function loadSandboxLibraries(): Promise<SandboxLibraryBundle> {
  if (!cached) {
    cached = import('./bundle.generated').then((mod) => ({
      sources: mod.LIBRARY_SOURCES,
      globalNames: mod.LIBRARY_GLOBAL_NAMES,
      prelude: mod.SANDBOX_PRELUDE,
    }));
  }
  return cached;
}

/**
 * Source for the `require()` shim inside QuickJS. After every library
 * IIFE has run (each one assigns its exports to its `globalThis.<name>`),
 * this shim looks up the global by the manifest key the user passed.
 */
export function buildRequireShimSource(globalNames: Record<string, string>): string {
  // Inline the manifest as a JSON object literal. The shim is a couple
  // dozen lines of plain JS — easier to read than building it via
  // QuickJS handle manipulation.
  return (
    'globalThis.__SANDBOX_REQUIRE_MAP = ' +
    JSON.stringify(globalNames) +
    ';\n' +
    `globalThis.__SANDBOX_REQUIRE_CACHE = {};\n` +
    `globalThis.require = function (name) {\n` +
    `  if (globalThis.__SANDBOX_REQUIRE_CACHE[name] !== undefined) {\n` +
    `    return globalThis.__SANDBOX_REQUIRE_CACHE[name];\n` +
    `  }\n` +
    `  var globalName = globalThis.__SANDBOX_REQUIRE_MAP[name];\n` +
    `  if (!globalName) {\n` +
    `    throw new Error("Cannot find module '" + name + "'");\n` +
    `  }\n` +
    `  var mod = globalThis[globalName];\n` +
    `  if (mod === undefined) {\n` +
    `    throw new Error("Module '" + name + "' was registered but its source did not load");\n` +
    `  }\n` +
    `  // Unwrap esbuild's IIFE-default-export envelope: \`{ default: actual }\`\n` +
    `  // when the underlying entry was CJS \`module.exports = X\`. Postman's\n` +
    `  // contract is that \`require('lodash')\` returns the lodash function\n` +
    `  // directly, not \`{ default: lodash }\`.\n` +
    `  var unwrapped = (mod && typeof mod === 'object' && 'default' in mod && Object.keys(mod).length === 1)\n` +
    `    ? mod.default : mod;\n` +
    `  globalThis.__SANDBOX_REQUIRE_CACHE[name] = unwrapped;\n` +
    `  return unwrapped;\n` +
    `};\n`
  );
}
