// Builds the machine- and human-readable map of the running stack: every URL,
// the credentials each auth endpoint expects, and the cert paths to import for
// TLS/mTLS. Creds come straight from e2e/mocks/authRoutes (TEST_AUTH_FIXTURES)
// so they can never drift from what the servers actually validate.

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { TEST_AUTH_FIXTURES } from '../e2e/mocks/authRoutes';
import { PORTS } from './ports';
import type { EchoCerts } from './certs';

export interface Manifest {
  host: string;
  generatedNote: string;
  endpoints: Record<string, string>;
  credentials: typeof TEST_AUTH_FIXTURES;
  tls: {
    caCert: string;
    clientCert: string;
    clientKey: string;
    clientPfx: string;
    clientPfxPassphrase: string;
    importHint: string;
  } | null;
  manual: Record<string, unknown>;
}

export function buildManifest(opts: { host: string; certs?: EchoCerts | undefined }): Manifest {
  const { host } = opts;
  const http = `http://${host}:${PORTS.http}`;
  const https = `https://${host}:${PORTS.https}`;

  return {
    host,
    generatedNote: 'Generated by `npm run echo:local`. Safe to delete.',
    endpoints: {
      http,
      https,
      mtls: `https://${host}:${PORTS.mtls}  (requires client cert)`,
      'mtls.whoami': `https://${host}:${PORTS.mtls}/mtls/whoami`,
      graphql: `${http}/graphql  (POST; query/mutation — Query.users, hello, user, boom)`,
      sse: `${http}/stream/sse  (also /stream/sse-named /stream/sse-resume /stream/sse-comments)`,
      proxy: `http://${host}:${PORTS.proxy}  (HTTP forward + CONNECT)`,
      grpc: `grpc://${host}:${PORTS.grpc}  (echo.v1.EchoService, reflection on)`,
      ws: `ws://${host}:${PORTS.ws}/echo  (also /chat /graphql sub /ping /close)`,
      wss: `wss://${host}:${PORTS.wss}/echo  (same paths over TLS — what the packaged desktop CSP allows)`,
      socketio: `http://${host}:${PORTS.socketio}  (namespaces / /chat /admin)`,
      mcp: `http://${host}:${PORTS.mcp}/mcp  (streamable-http)`,
      mqtt: `mqtt://${host}:${PORTS.mqtt}  (EMQX MQTT 5 — start via docker compose)`,
      mqtts: `mqtts://${host}:${PORTS.mqtts}  (EMQX self-signed cert — verify-SSL off)`,
      mqttDashboard: `http://${host}:${PORTS.mqttDashboard}  (EMQX dashboard — admin / public)`,
      kafka: `${host}:${PORTS.kafka}  (Apache Kafka KRaft — start via docker compose)`,
      'oauth.wellKnown': `${http}/.well-known/openid-configuration`,
      'oauth.token': `${http}/oauth/token`,
      'oauth.authorize': `${http}/oauth/authorize`,
      'auth.awsProtected': `${http}/aws/protected`,
      'auth.wsseProtected': `${http}/wsse/protected  (verifies the X-WSSE UsernameToken digest)`,
      'auth.digest': `${http}/digest-auth/${TEST_AUTH_FIXTURES.user.username}/${TEST_AUTH_FIXTURES.user.password}`,
    },
    credentials: TEST_AUTH_FIXTURES,
    tls: opts.certs
      ? {
          caCert: opts.certs.caCertPath,
          clientCert: opts.certs.clientCertPath,
          clientKey: opts.certs.clientKeyPath,
          clientPfx: opts.certs.clientPfxPath,
          clientPfxPassphrase: opts.certs.clientPfxPassphrase,
          importHint:
            'Settings → import the CA into custom-CA; attach client cert+key (or the .p12 with the passphrase) for mTLS.',
        }
      : null,
    manual: {
      websocket: {
        note: 'WebSocket is connection-based — connect manually (not a collection request). Both ws:// and wss:// (CA-signed) are served; the packaged desktop CSP allows wss: only, so use wss for packaged-build testing.',
        echo: `ws://${host}:${PORTS.ws}/echo`,
        echoSecure: `wss://${host}:${PORTS.wss}/echo  (import the CA, or verify-SSL off)`,
        chat: `ws://${host}:${PORTS.ws}/chat  (broadcasts to OTHER peers — open two connections to observe)`,
        ping: `ws://${host}:${PORTS.ws}/ping  (send "PING_ME" then "REPORT")`,
        close: `ws://${host}:${PORTS.ws}/close?code=4001&reason=bye`,
        graphqlSubscriptions: `ws://${host}:${PORTS.ws}/graphql`,
      },
      socketio: {
        url: `http://${host}:${PORTS.socketio}`,
        namespaces: {
          default: '/',
          chat: '/chat (broadcasts to other peers)',
          admin: '/admin (auth.token=admin-token)',
        },
      },
      mqtt: {
        url: `mqtt://${host}:${PORTS.mqtt}`,
        start: 'docker compose -f echo-local/docker-compose.yml up -d',
        try: 'subscribe to "test/#", then publish to "test/echo" — it round-trips.',
        note:
          'EMQX broker (Docker) — full MQTT 5 + 3.1.1, anonymous connect allowed. Dashboard at :' +
          PORTS.mqttDashboard +
          ' (admin / public).',
        caveat:
          'mqtts (:8883) presents EMQX’s built-in self-signed cert (not the local CA) — connect with verify-SSL off. Custom-CA + mTLS are covered by the HTTPS :8443/:8444 services.',
      },
      kafka: {
        bootstrap: `${host}:${PORTS.kafka}`,
        group: 'echo-group',
        start: 'docker compose -f echo-local/docker-compose.yml up -d',
        try: 'create topic "echo", produce, then consume from earliest.',
        caveat:
          'PLAINTEXT only, no Schema Registry. SASL (PLAIN/SCRAM), SSL/SASL_SSL, and Avro/Protobuf/JSON-via-registry cannot be tested against this broker.',
      },
      httpLimitations: {
        multipartAndBinary:
          'form-data (multipart) and binary request bodies are not sendable from the desktop UI today — /upload and binary-echo are not exercisable.',
      },
      lossyAuth: {
        oauth1:
          'Imports as no-auth (OpenCollection lossy) — configure manually. The client signs it at the wire; no server endpoint verifies the signature (the HMAC-SHA1 base string lives inside the oauth-1.0a package, so a faithful verifier can’t share the signer’s logic).',
        wsse: 'Imports as no-auth (OpenCollection lossy) — configure manually (PasswordDigest). GET /wsse/protected verifies the X-WSSE UsernameToken digest end-to-end.',
        oauth2:
          'Token fetch uses a renderer fetch() blocked by the packaged-build CSP for http://. Use the dev build (npm run electron:dev) for OAuth2 against :8080, or it only works unpackaged.',
        digest: 'Server supports it, but the desktop client transport does not apply Digest yet.',
        ntlm: 'Not implemented in the desktop client transport.',
      },
    },
  };
}

export function writeManifest(manifest: Manifest, dir: string): string {
  const path = join(dir, 'manifest.json');
  writeFileSync(path, JSON.stringify(manifest, null, 2));
  return path;
}

export function printManifest(manifest: Manifest): void {
  const line = '─'.repeat(64);
  console.log('');
  console.log(`  Restura local echo stack — ${manifest.host}`);
  console.log(`  ${line}`);
  for (const [name, value] of Object.entries(manifest.endpoints)) {
    console.log(`  ${name.padEnd(20)} ${value}`);
  }
  console.log(`  ${line}`);
  console.log('  Credentials');
  console.log(
    `     OAuth client   ${manifest.credentials.client.id} / ${manifest.credentials.client.secret}`
  );
  console.log(
    `     User           ${manifest.credentials.user.username} / ${manifest.credentials.user.password}`
  );
  console.log(
    `     AWS SigV4      ${manifest.credentials.aws.accessKey} (${manifest.credentials.aws.region}/${manifest.credentials.aws.service})`
  );
  if (manifest.tls) {
    console.log('  TLS / mTLS');
    console.log(`     Import CA      ${manifest.tls.caCert}`);
    console.log(`     Client cert    ${manifest.tls.clientCert}`);
    console.log(`     Client key     ${manifest.tls.clientKey}`);
    console.log(
      `     Client .p12    ${manifest.tls.clientPfx}  (pass: ${manifest.tls.clientPfxPassphrase})`
    );
  }
  console.log(`  ${line}`);
  console.log('  Full detail in echo-local/manifest.json');
  console.log('');
}
