import type { ArchitecturePolicy } from './architecture-policy.mts';

export const architecturePolicy: ArchitecturePolicy = {
  zones: [
    { name: 'shared', root: 'shared/' },
    { name: 'renderer', root: 'src/' },
    { name: 'worker', root: 'worker/' },
    { name: 'electron-main', root: 'electron/main/' },
    { name: 'electron-shared', root: 'electron/shared/' },
    { name: 'electron-types', root: 'electron/types/' },
    { name: 'cli', root: 'cli/src/' },
    { name: 'extensions', root: 'extension/' },
    { name: 'echo', root: 'echo/' },
    { name: 'echo-local', root: 'echo-local/' },
    { name: 'tooling', root: 'scripts/' },
  ],
  forbiddenDependencies: [
    { from: 'shared', to: 'renderer' },
    { from: 'shared', to: 'worker' },
    { from: 'shared', to: 'electron-main' },
    { from: 'shared', to: 'cli' },
    { from: 'shared', to: 'extensions' },
    { from: 'shared', to: 'electron-types' },
    { from: 'shared', to: 'echo' },
    { from: 'shared', to: 'echo-local' },
    { from: 'shared', to: 'tooling' },
    { from: 'worker', to: 'renderer' },
    { from: 'worker', to: 'electron-main' },
    { from: 'renderer', to: 'worker' },
    { from: 'renderer', to: 'electron-main' },
    { from: 'electron-main', to: 'renderer' },
    { from: 'electron-shared', to: 'renderer' },
    { from: 'electron-shared', to: 'worker' },
    { from: 'electron-shared', to: 'electron-main' },
    { from: 'electron-shared', to: 'electron-types' },
    { from: 'electron-shared', to: 'cli' },
    { from: 'electron-shared', to: 'extensions' },
    { from: 'electron-shared', to: 'echo' },
    { from: 'electron-shared', to: 'echo-local' },
    { from: 'electron-shared', to: 'tooling' },
    { from: 'electron-types', to: 'renderer' },
    { from: 'electron-types', to: 'worker' },
    { from: 'electron-types', to: 'electron-main' },
    { from: 'electron-types', to: 'cli' },
    { from: 'electron-types', to: 'extensions' },
    { from: 'cli', to: 'renderer' },
    { from: 'extensions', to: 'renderer' },
    { from: 'echo', to: 'renderer' },
    { from: 'echo-local', to: 'renderer' },
  ],
  allowedDependencies: [],
  maxNewProductionFileLines: 800,
  grandfatheredFileLines: {
    'src/features/settings/SettingsDrawer.tsx': 2_322,
    'src/features/kafka/components/KafkaClient.tsx': 1_554,
    'src/features/collections/components/Sidebar.tsx': 1_581,
    'shared/scripts/script-executor.ts': 1_537,
    'electron/main/handlers/http-handler.ts': 1_240,
    'src/features/mcp/components/McpRequestBuilder.tsx': 1_027,
    'src/features/http/components/NetworkConsole/NetworkTab.tsx': 1_046,
    'src/features/mqtt/components/MqttClient.tsx': 1_007,
    'src/features/auth/components/AuthConfig.tsx': 950,
    'src/features/ai-lab/components/EvalBuilder.tsx': 912,
    'src/features/ai-lab/components/ProviderManager.tsx': 861,
    'electron/main/handlers/kafka-handler.ts': 867,
    'electron/main/handlers/grpc-connect.ts': 819,
    'src/components/shared/ImportDialog.tsx': 816,
    'src/features/ai-lab/components/ReportView.tsx': 801,
  },
};
