import type { ArchitecturePolicy } from './architecture-policy.mts';

export const architecturePolicy: ArchitecturePolicy = {
  zones: [
    { name: 'shared', root: 'shared/' },
    { name: 'renderer', root: 'src/' },
    { name: 'worker', root: 'worker/' },
    { name: 'electron-main', root: 'electron/main/' },
    { name: 'electron-shared', root: 'electron/shared/' },
    { name: 'electron-types', root: 'electron/types/' },
    { name: 'cli', root: 'cli/src/' },
    { name: 'extensions', root: 'extension/' },
    { name: 'echo', root: 'echo/' },
    { name: 'echo-local', root: 'echo-local/' },
    { name: 'tooling', root: 'scripts/' },
  ],
  forbiddenDependencies: [
    { from: 'shared', to: 'renderer' },
    { from: 'shared', to: 'worker' },
    { from: 'shared', to: 'electron-main' },
    { from: 'shared', to: 'cli' },
    { from: 'shared', to: 'extensions' },
    { from: 'shared', to: 'electron-types' },
    { from: 'shared', to: 'echo' },
    { from: 'shared', to: 'echo-local' },
    { from: 'shared', to: 'tooling' },
    { from: 'worker', to: 'renderer' },
    { from: 'worker', to: 'electron-main' },
    { from: 'renderer', to: 'worker' },
    { from: 'renderer', to: 'electron-main' },
    { from: 'electron-main', to: 'renderer' },
    { from: 'electron-shared', to: 'renderer' },
    { from: 'electron-shared', to: 'worker' },
    { from: 'electron-shared', to: 'electron-main' },
    { from: 'electron-shared', to: 'electron-types' },
    { from: 'electron-shared', to: 'cli' },
    { from: 'electron-shared', to: 'extensions' },
    { from: 'electron-shared', to: 'echo' },
    { from: 'electron-shared', to: 'echo-local' },
    { from: 'electron-shared', to: 'tooling' },
    { from: 'electron-types', to: 'renderer' },
    { from: 'electron-types', to: 'worker' },
    { from: 'electron-types', to: 'electron-main' },
    { from: 'electron-types', to: 'cli' },
    { from: 'electron-types', to: 'extensions' },
    { from: 'cli', to: 'renderer' },
    { from: 'extensions', to: 'renderer' },
    { from: 'echo', to: 'renderer' },
    { from: 'echo-local', to: 'renderer' },
  ],
  allowedDependencies: [],
  maxNewProductionFileLines: 800,
  grandfatheredFileLines: {
    'shared/scripts/script-executor.ts': 1_195,
    'electron/main/handlers/http-handler.ts': 981,
    'electron/main/handlers/kafka-handler.ts': 728,
    'electron/main/handlers/grpc-connect.ts': 819,
  },
  // Type scale (UI/UX Phase 6): sizes come from the text-sp-* tokens, 11px
  // minimum. Both counts may only go down.
  sourcePatternRatchets: [
    {
      name: 'arbitrary pixel font sizes (text-[Npx])',
      pathPrefix: 'src/',
      extension: '.tsx',
      pattern: String.raw`\btext-\[\d+(?:\.\d+)?px\]`,
      max: 86,
    },
    {
      name: 'sub-11px type tokens (text-sp-9 / text-sp-10 / text-sp-10-5)',
      pathPrefix: 'src/',
      extension: '.tsx',
      pattern: String.raw`\btext-sp-(?:9|10)(?:-5)?\b`,
      max: 93,
    },
  ],
};
